### ISSUE TITLE
What version of GOCD does this work ?

### ISSUE THREAD

**Issue by akramwaseem** [leprechaun/gocd-prometheus-exporter#8]
Hi, 
I am trying to make this exporter work.Seems I have some issues with it.
gocd is outside of the kubernetes.

Traceback (most recent call last):
  File "/usr/local/bin/gocd_prometheus", line 294, in <module>
    tree = ET.fromstring(xml.text.encode('utf-8'))
  File "/usr/local/lib/python2.7/xml/etree/ElementTree.py", line 1311, in XML
    parser.feed(text)
  File "/usr/local/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/local/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: mismatched tag: line 39, column 2

not sure if this is python issue or gocd , we are using 18.3

**Comment by MPV** [comment]
The last line in the stack trace shows that it fails when trying to read your CCtray XML file. Apparently as `mismatched tag at line 39, character 2`.

Could you share what's in your CCtray.xml file at this line? 

You can find it a link to your cctray in the bottom right corner of your GoCD server web UI.

**Comment by leprechaun** [comment]
While logging/debugging ain't quite there yet, I did get that kind of error when I had Auth, or SSL issues, which meant that `xml.text` really wasn't xml at all.

**Comment by akramwaseem** [comment]
I made it work. It was a yaml issue.Thanks though.
Also I was wondering if I can ping my gocd url or curl it. right know I can only see metrics for pipelines. 
that would be a neat feature.

**Comment by leprechaun** [comment]
I'm not sure I understand. You want this exporter to curl / ping gocd? What are you trying to get visibility on? What metrics/numbers are you after with this?

**Comment by leprechaun** [comment]
I see what you mean, and it's not a bad idea, and wouldn't cost much to implement; I just might add it.

However, this is the kind of thing that might better live *with* GoCD, as a plugin, instead of outside.

**Comment by akramwaseem** [comment]
@leprechaun  -- thanks
